/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package captain;

import crew.CrewGui;
import java.util.ArrayList;

/**
 *
 * @author Luk
 */
public class Gui extends javax.swing.JFrame {

    int counter = 0;
    ArrayList<CrewGui> players = new ArrayList();

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crewListComboBox = new javax.swing.JComboBox<>();
        kickButton = new javax.swing.JButton();
        newPlayertextField = new java.awt.TextField();
        addPlayerButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        engineCheckBox = new javax.swing.JCheckBox();
        coolingCheckBox = new javax.swing.JCheckBox();
        turboCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        powerCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        powerLevelSlider = new javax.swing.JSlider();
        sendButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statisticsTextArea = new javax.swing.JTextArea();
        sendAllButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Captain Panel");

        kickButton.setText("Disconnect");
        kickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kickButtonActionPerformed(evt);
            }
        });

        newPlayertextField.setText("player");

        addPlayerButton.setText("Add player");
        addPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        checkButton.setText("End round");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Engine:");

        jLabel2.setText("Cooling:");

        jLabel3.setText("Turbo:");

        jLabel4.setText("Power:");

        jLabel5.setText("Power Level:");

        powerLevelSlider.setMaximum(3);
        powerLevelSlider.setValue(0);

        sendButton.setText("Send command");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Statistics:");

        statisticsTextArea.setColumns(20);
        statisticsTextArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statisticsTextArea.setRows(5);
        jScrollPane1.setViewportView(statisticsTextArea);

        sendAllButton.setText("Send to all");
        sendAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAllButtonActionPerformed(evt);
            }
        });

        jButton1.setText("End game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newPlayertextField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(crewListComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kickButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5)
                    .addComponent(powerLevelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendAllButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(engineCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(coolingCheckBox)
                                    .addComponent(turboCheckBox)
                                    .addComponent(powerCheckBox))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crewListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kickButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPlayertextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPlayerButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(engineCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(coolingCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(turboCheckBox))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(checkButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powerCheckBox)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(powerLevelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendButton)
                            .addComponent(sendAllButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
        CrewGui cm = new CrewGui(newPlayertextField.getText(), counter);
        players.add(cm);
        counter++;
        crewListComboBox.addItem(newPlayertextField.getText());
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void kickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kickButtonActionPerformed
        int id = crewListComboBox.getSelectedIndex();
        players.get(id).dispose();
        players.remove(id);
    }//GEN-LAST:event_kickButtonActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        String out="";
        for (CrewGui player : players) {
            out += player.getPlayersName() + ":\t" + player.getScore() + "\n";
        }
        statisticsTextArea.setText(out);
    }//GEN-LAST:event_checkButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        int id = crewListComboBox.getSelectedIndex();
        String command = players.get(id).getPlayersName() + "! " + "Your task is to set"
                + " cooling to " + coolingCheckBox.isSelected()
                + ", engine to " + engineCheckBox.isSelected()
                + ",\n turbo to " + turboCheckBox.isSelected()
                + ", power to " + powerCheckBox.isSelected()
                + ", power level to " + powerLevelSlider.getValue()
                + ". Good luck!";
        players.get(id).setInputCoolingStatus(coolingCheckBox.isSelected());
        players.get(id).setInputEngineStatus(engineCheckBox.isSelected());
        players.get(id).setInputTurboStatus(turboCheckBox.isSelected());
        players.get(id).setInputPowerStatus(powerCheckBox.isSelected());
        players.get(id).setInputPowerLevelStatus(powerLevelSlider.getValue());
        players.get(id).setCommandTextArea(command);
    }//GEN-LAST:event_sendButtonActionPerformed

    private void sendAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAllButtonActionPerformed
       for (CrewGui player : players) {
        String command = player.getPlayersName() + "! " + "Your task is to set"
                + " cooling to " + coolingCheckBox.isSelected()
                + ", engine to " + engineCheckBox.isSelected()
                + ",\n turbo to " + turboCheckBox.isSelected()
                + ", power to " + powerCheckBox.isSelected()
                + ", power level to " + powerLevelSlider.getValue()
                + ". Good luck!";
        player.setInputCoolingStatus(coolingCheckBox.isSelected());
        player.setInputEngineStatus(engineCheckBox.isSelected());
        player.setInputTurboStatus(turboCheckBox.isSelected());
        player.setInputPowerStatus(powerCheckBox.isSelected());
        player.setInputPowerLevelStatus(powerLevelSlider.getValue());
        player.setCommandTextArea(command);
       }
    }//GEN-LAST:event_sendAllButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String out="";
        for (CrewGui player : players) {
            out += player.getPlayersName() + ":\t" + player.getScore() + "\n";
        }
        statisticsTextArea.setText(out);
        for (CrewGui player : players) {
        player.dispose();
        }
        players.removeAll(players);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JCheckBox coolingCheckBox;
    private javax.swing.JComboBox<String> crewListComboBox;
    private javax.swing.JCheckBox engineCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kickButton;
    private java.awt.TextField newPlayertextField;
    private javax.swing.JCheckBox powerCheckBox;
    private javax.swing.JSlider powerLevelSlider;
    private javax.swing.JButton sendAllButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea statisticsTextArea;
    private javax.swing.JCheckBox turboCheckBox;
    // End of variables declaration//GEN-END:variables
}
